### ISSUE TITLE
Improvement: Optimize png resources

### ISSUE THREAD

**Issue by jummy0** [Brian-Mp16/Animal-Crossing-Town-Ticket-Station#5]
`optipng --strip all` losslessly reduces the Resources directory from 117 MB to 92 MB.
i couldn't find github's filesize limit for Releases, but one source states 100 MB, which is no longer exceeded with these optimizations.

**Comment by Brian-Mp16** [comment]
Good to know, I'll look into the optipng software for a future update.

EDIT: I have successfully applied optipng and reduced the file size of the program below 100MB as of v.1.2.6. Thank you for the suggestion
